// Uncovered is a command-line tool that analyzes Go test coverage profiles
// and displays uncovered lines with surrounding context.
//
// The tool reads a coverage profile generated by `go test -coverprofile`,
// identifies lines that were not executed during testing, and presents them
// with context lines before and after for better understanding.
//
// # Usage
//
// Generate a coverage profile and run uncovered:
//
//	go test -coverprofile=coverage.out ./...
//	uncovered coverage.out
//
// # Output Format
//
// The output shows each file with uncovered lines, displaying:
//   - File name with statistics (e.g., "29 of 59 lines uncovered")
//   - Context lines (3 lines before and after each uncovered section)
//   - Uncovered lines marked with ">" in red
//   - Line numbers for easy navigation
//
// # How It Works
//
// 1. Parses the coverage profile to extract coverage blocks
// 2. Finds the module path from go.mod to resolve file paths
// 3. Identifies blocks with zero execution count (uncovered)
// 4. Groups nearby uncovered lines to avoid repetitive context
// 5. Renders each file with colored output and line numbers
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/hanpama/uncovered/coverage"
	"github.com/hanpama/uncovered/gomod"
	"github.com/hanpama/uncovered/renderer"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	// Parse command-line flags
	flag.Usage = usage
	flag.Parse()

	// Get coverage profile path from arguments
	args := flag.Args()
	if len(args) == 0 {
		flag.Usage()
		return fmt.Errorf("coverprofile argument is required")
	}
	coverProfile := args[0]

	// Open coverage profile
	file, err := os.Open(coverProfile)
	if err != nil {
		return fmt.Errorf("opening coverage profile: %w", err)
	}
	defer file.Close()

	// Parse coverage profile
	profile, err := coverage.ParseProfile(file)
	if err != nil {
		return fmt.Errorf("parsing coverage profile: %w", err)
	}

	// Find module path from go.mod
	modulePath, err := gomod.FindModulePath()
	if err != nil {
		return fmt.Errorf("finding module path: %w", err)
	}

	// Convert module paths to relative paths
	for _, block := range profile.Blocks {
		block.FileName = gomod.ConvertToRelativePath(block.FileName, modulePath)
	}

	// Get uncovered lines
	uncovered := coverage.GetUncoveredLines(profile)

	if len(uncovered) == 0 {
		fmt.Println("No uncovered lines found!")
		return nil
	}

	// Render uncovered lines with context
	r := renderer.New()
	if err := r.Render(os.Stdout, uncovered); err != nil {
		return fmt.Errorf("rendering: %w", err)
	}

	return nil
}

func usage() {
	fmt.Fprintf(os.Stderr, `uncovered - Show uncovered lines from Go test coverage with context

Usage:
  uncovered <coverprofile>

Arguments:
  coverprofile    Path to coverage profile file

Examples:
  # Generate coverage and show uncovered lines
  go test -coverprofile=coverage.out ./...
  uncovered coverage.out

  # Use custom coverage file
  uncovered custom.out
`)
}
