// Package gomod provides utilities for parsing go.mod files and resolving
// module-relative file paths.
//
// Coverage profiles generated by `go test -coverprofile` use full module
// paths for file names (e.g., "github.com/user/repo/pkg/file.go"). This
// package helps convert those paths to relative file paths that can be
// opened from the current directory.
//
// # Example
//
// If go.mod contains:
//
//	module github.com/user/repo
//
// Then a coverage profile entry like:
//
//	github.com/user/repo/pkg/file.go:10.5,12.2 1 0
//
// Will be converted to the relative path:
//
//	pkg/file.go
package gomod

import (
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/mod/modfile"
)

// FindModulePath finds the module path by searching for go.mod.
//
// It starts from the current working directory and searches upward through
// parent directories until it finds a go.mod file. The module path is
// extracted from the "module" directive in that file.
//
// Returns an empty string if no go.mod file is found.
func FindModulePath() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		modFile := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(modFile); err == nil {
			return parseModulePath(modFile)
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			// Reached root
			return "", nil
		}
		dir = parent
	}
}

// parseModulePath extracts the module path from go.mod file
func parseModulePath(modFilePath string) (string, error) {
	data, err := os.ReadFile(modFilePath)
	if err != nil {
		return "", err
	}

	mod, err := modfile.Parse(modFilePath, data, nil)
	if err != nil {
		return "", err
	}

	if mod.Module == nil {
		return "", nil
	}

	return mod.Module.Mod.Path, nil
}

// ConvertToRelativePath converts a full module path to a relative file path.
//
// Given a file path from a coverage profile that includes the module path prefix,
// this function strips the module path and returns just the relative portion.
//
// For example, with modulePath "github.com/hanpama/uncovered":
//
//	"github.com/hanpama/uncovered/example/calculator.go" -> "example/calculator.go"
//
// If the file path doesn't start with the module path, it is returned unchanged.
func ConvertToRelativePath(fullPath, modulePath string) string {
	if modulePath == "" {
		return fullPath
	}

	prefix := modulePath + "/"
	if after, found := strings.CutPrefix(fullPath, prefix); found {
		return after
	}

	return fullPath
}
